FROM maven:3.8.5-openjdk-17 as build
COPY biddingSys .
RUN mvn clean package -DskipTests

FROM openjdk:17.0.2-jdk-slim
COPY --from=build /target/demo.0.0.1-SNAPSHOT.jar biddingSys.jar
EXPOSE 9000
ENTRYPOINT ["java","-jar","biddingSys.jar"]